INSERT INTO [dbo].[Corso] ([CodiceCorso], [Descrizione], [Livello], [CodiceSede]) VALUES (1, N'Bambini', N'Base', 1)
INSERT INTO [dbo].[Corso] ([CodiceCorso], [Descrizione], [Livello], [CodiceSede]) VALUES (2, N'Adulti', N'Base', 1)
INSERT INTO [dbo].[Corso] ([CodiceCorso], [Descrizione], [Livello], [CodiceSede]) VALUES (3, N'Bambini', N'Avanzato', 2)
INSERT INTO [dbo].[Corso] ([CodiceCorso], [Descrizione], [Livello], [CodiceSede]) VALUES (4, N'Bambini', N'Base', 3)
INSERT INTO [dbo].[Corso] ([CodiceCorso], [Descrizione], [Livello], [CodiceSede]) VALUES (5, N'Bambini', N'Avanzato', 4)
