//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkateSchool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestito
    {
        public int CodiceIscritto { get; set; }
        public int CodiceAttrezzatura { get; set; }
        public System.DateTime Data { get; set; }
        public bool Restituito { get; set; }
    
        public virtual Attrezzatura Attrezzatura { get; set; }
        public virtual Iscritto Iscritto { get; set; }
    }
}
