INSERT INTO [dbo].[Iscritto] ([CodiceIscritto], [Nome], [Cognome], [Eta], [Telefono], [Livello]) VALUES (1, N'Sara', N'Cappelletti', 20, N'3356894488', N'base')
INSERT INTO [dbo].[Iscritto] ([CodiceIscritto], [Nome], [Cognome], [Eta], [Telefono], [Livello]) VALUES (2, N'Gabriele', N'Neri', 12, N'3379757733', N'avanzato')
INSERT INTO [dbo].[Iscritto] ([CodiceIscritto], [Nome], [Cognome], [Eta], [Telefono], [Livello]) VALUES (3, N'Claudia', N'Castellucci', 30, N'3378649528', N'adulti avanzato')
INSERT INTO [dbo].[Iscritto] ([CodiceIscritto], [Nome], [Cognome], [Eta], [Telefono], [Livello]) VALUES (4, N'Giulio ', N'Giorgetti', 10, N'3367953920', N'avanzato')
INSERT INTO [dbo].[Iscritto] ([CodiceIscritto], [Nome], [Cognome], [Eta], [Telefono], [Livello]) VALUES (5, N'Alfredo', N'Furini', 13, N'3375893377', N'avanzato')
