//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkateSchool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lezione
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lezione()
        {
            this.Iscritti = new HashSet<Iscritto>();
        }
    
        public int CodiceLezione { get; set; }
        public int CodiceIstruttore { get; set; }
        public int CodiceCorso { get; set; }
        public int MassimoPartecipanti { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual Corso Corso { get; set; }
        public virtual Istruttore Istruttori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Iscritto> Iscritti { get; set; }
    }
}
