//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkateSchool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oggetto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Oggetto()
        {
            this.Vendite = new HashSet<Vendita>();
        }
    
        public int CodiceOggetto { get; set; }
        public int Quantita { get; set; }
        public float Prezzo { get; set; }
        public string Descrizione { get; set; }
        public int CodiceSede { get; set; }
        public int CodiceTipo { get; set; }
    
        public virtual TipologiaOggetto TipologiaOggetto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vendita> Vendite { get; set; }
        public virtual Sede Sedi { get; set; }
    }
}
