//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkateSchool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendita
    {
        public int CodiceVendita { get; set; }
        public int CodiceOggetto { get; set; }
        public int Quantita { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual Oggetto Oggetto { get; set; }
    }
}
